//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 09:07:51 AM MST 
//


package com.viasat.internalservice.mbeancollector.persistence.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for configType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="configType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="collectorConfig" type="{}collectorConfigType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "configType", propOrder = {
    "collectorConfig"
})
public class ConfigType {

    @XmlElement(required = true)
    protected CollectorConfigType collectorConfig;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the collectorConfig property.
     * 
     * @return
     *     possible object is
     *     {@link CollectorConfigType }
     *     
     */
    public CollectorConfigType getCollectorConfig() {
        return collectorConfig;
    }

    /**
     * Sets the value of the collectorConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollectorConfigType }
     *     
     */
    public void setCollectorConfig(CollectorConfigType value) {
        this.collectorConfig = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
