//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 09:07:51 AM MST 
//


package com.viasat.internalservice.mbeancollector.persistence.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.viasat.internalservice.mbeancollector.persistence.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Config_QNAME = new QName("", "config");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.viasat.internalservice.mbeancollector.persistence.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CollectionInfosType }
     * 
     */
    public CollectionInfosType createCollectionInfosType() {
        return new CollectionInfosType();
    }

    /**
     * Create an instance of {@link ConfigType }
     * 
     */
    public ConfigType createConfigType() {
        return new ConfigType();
    }

    /**
     * Create an instance of {@link TagType }
     * 
     */
    public TagType createTagType() {
        return new TagType();
    }

    /**
     * Create an instance of {@link CredentialsType }
     * 
     */
    public CredentialsType createCredentialsType() {
        return new CredentialsType();
    }

    /**
     * Create an instance of {@link MetricDefinitionsType }
     * 
     */
    public MetricDefinitionsType createMetricDefinitionsType() {
        return new MetricDefinitionsType();
    }

    /**
     * Create an instance of {@link MetricDefinitionType }
     * 
     */
    public MetricDefinitionType createMetricDefinitionType() {
        return new MetricDefinitionType();
    }

    /**
     * Create an instance of {@link DataBusConfigType }
     * 
     */
    public DataBusConfigType createDataBusConfigType() {
        return new DataBusConfigType();
    }

    /**
     * Create an instance of {@link CollectorConfigType }
     * 
     */
    public CollectorConfigType createCollectorConfigType() {
        return new CollectorConfigType();
    }

    /**
     * Create an instance of {@link TagsType }
     * 
     */
    public TagsType createTagsType() {
        return new TagsType();
    }

    /**
     * Create an instance of {@link CollectionSourceType }
     * 
     */
    public CollectionSourceType createCollectionSourceType() {
        return new CollectionSourceType();
    }

    /**
     * Create an instance of {@link CollectionInfoType }
     * 
     */
    public CollectionInfoType createCollectionInfoType() {
        return new CollectionInfoType();
    }

    /**
     * Create an instance of {@link CollectorKeyType }
     * 
     */
    public CollectorKeyType createCollectorKeyType() {
        return new CollectorKeyType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "config")
    public JAXBElement<ConfigType> createConfig(ConfigType value) {
        return new JAXBElement<ConfigType>(_Config_QNAME, ConfigType.class, null, value);
    }

}
