package com.viasat.wildblue.common.adapter;

import java.util.Calendar;

import javax.xml.bind.annotation.adapters.XmlAdapter;

/**
 * Essentially a copied class generated by jaxb. Needed to not be generated in
 * order to avoid name conflicts.
 * 
 * If you need {@link java.util.Date} instead of Calendars use:
 * {@link com.viasat.commonxsd.adapter.XmlDateToJavaDate} and/or
 * {@link com.viasat.commonxsd.adapter.XmlDateTimeToJavaDate}
 */
public class XmlDateToCalendarAdapter extends XmlAdapter<String, Calendar>
{
	/**
	 * @see javax.xml.bind.annotation.adapters.XmlAdapter#marshal(java.lang.Object)
	 */
	@Override
	public String marshal(Calendar value)
	{
		if (value == null)
		{
			return null;
		}

		return (javax.xml.bind.DatatypeConverter.printDate(value));
	}

	/**
	 * @see javax.xml.bind.annotation.adapters.XmlAdapter#unmarshal(java.lang.Object)
	 */
	@Override
	public Calendar unmarshal(String value)
	{
		if (value != null && value.length() > 0)
		{
			return (javax.xml.bind.DatatypeConverter.parseDate(value));
		}
		else
			return null;
	}
}
